language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - libssl-dev
before_install:
  - export OPAMYES=1
  - opam init
  - opam install -q -y ocamlfind base-bytes
  - eval `opam config env`

script: ./bootstrap && ./configure && make && examples/configure --with-ssl-dir=../src && make -C examples
